# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# compile CXX with /usr/bin/c++
CXX_FLAGS = -std=c++11 -g  

CXX_DEFINES = 

CXX_INCLUDES = -I/home/c2214/Projects/ACADOtoolkit -I/home/c2214/Projects/ACADOtoolkit/acado -I/home/c2214/Projects/ACADOtoolkit/external_packages -I/home/c2214/Projects/ACADOtoolkit/external_packages/qpOASES-3.2.0/include -I/home/c2214/Projects/ACADOtoolkit/build 

